tf.argmax()
==========

In [3]:
import tensorflow as tf
B = [ [ 3,  7,  2 ,99,200,3],
      [10, 20, 30 ,1 ,  3,2 ]]

m = tf.argmax(B)

print tf.Session().run(m)

m = tf.argmax(B, 1)
print tf.Session().run(m)

[1 1 1 0 0 0]
[4 2]


tf.reshape()
==============

In [1]:
import tensorflow as tf

n_input = 784 # MNIST data input (img shape: 28*28)

# tf Graph input
x = tf.placeholder(tf.float32, [None, n_input])
print('x ---> ' + str(x))


# Reshape input picture
x = tf.reshape(x, shape=[-1, 28, 28, 1])
print('note -1 will be ?')
print('x ----afetr reshape--> ' + str(x))


x ---> Tensor("Placeholder:0", shape=(?, 784), dtype=float32)
note -1 will be ?
x ----afetr reshape--> Tensor("Reshape:0", shape=(?, 28, 28, 1), dtype=float32)


tf.dropout()
==============

REFER URL:
U1: https://www.tensorflow.org/api_docs/python/tf/nn/dropout
U2: http://www.jianshu.com/p/c9f66bc8f96c

1. 留下來的會  乘 1/keep_prob, 範例中keep_prob = 0.5，所以乘2

With probability keep_prob, outputs the input element scaled up by 1 / keep_prob, otherwise outputs 0

2. random的，每次結果都不一樣，可看Area A 比較Area B，一樣的程式碼，結果不一樣

3. (17/08/27) 結論是，每次DROPOUT的都不一樣，留著的*1/keep_prob


In [27]:
#---- Area A----#
import tensorflow as tf

# m = tf.Variable(tf.random_normal([3,3]))  
m = tf.constant(
    [[ 0.20629479, -0.489871,    0.36569953] ,
     [ 0.33093473, -0.26071212,  0.68235433],
     [-0.15986885, -1.8439554,   1.8478545 ]] )
# keep_prob = tf.placeholder(0.75) 
keep_prob = 0.5
d = tf.nn.dropout(m, keep_prob)

# Initializing the variables
init = tf.global_variables_initializer()


with tf.Session() as sess:
    sess.run(init)
    print('m -->')
    print m.eval()
    print('d(drop out with ' + str(keep_prob) + ') -->')
    print d.eval()

m -->
[[ 0.20629479 -0.489871    0.36569953]
 [ 0.33093473 -0.26071212  0.68235433]
 [-0.15986885 -1.8439554   1.8478545 ]]
d(drop out with 0.5) -->
[[ 0.41258958 -0.          0.73139906]
 [ 0.         -0.          0.        ]
 [-0.3197377  -3.6879108   3.69570899]]


In [4]:
#---- Area B----#
import tensorflow as tf

# m = tf.Variable(tf.random_normal([3,3]))  
m = tf.constant(
    [[ 0.20629479, -0.489871,    0.36569953] ,
     [ 0.33093473, -0.26071212,  0.68235433],
     [-0.15986885, -1.8439554,   1.8478545 ]] )
# keep_prob = tf.placeholder(0.75) 
keep_prob = 0.5
d = tf.nn.dropout(m, keep_prob)

# Initializing the variables
init = tf.global_variables_initializer()


with tf.Session() as sess:
    sess.run(init)
    print('m -->')
    print m.eval()
    print('d(drop out with ' + str(keep_prob) + ') -->')
    print d.eval()
    

m -->
[[ 0.20629479 -0.489871    0.36569953]
 [ 0.33093473 -0.26071212  0.68235433]
 [-0.15986885 -1.8439554   1.8478545 ]]
d(drop out with 0.5) -->
[[ 0.         -0.97974199  0.73139906]
 [ 0.         -0.52142423  0.        ]
 [-0.         -3.6879108   3.69570899]]


tf.cast()
=========
URL: https://www.tensorflow.org/api_docs/python/tf/cast

型態轉換

tensor `a` is [1.8, 2.2], dtype=tf.float

tf.cast(a, tf.int32) ==> [1, 2]  # dtype=tf.int32

# tf.add_n()

In [4]:
a = 1
b = 2
c = 3

s = tf.add_n([a,b, c])

tf.Session().run(s)

6

# tf.slice()

In [8]:

import tensorflow as tf  
import numpy as np  
x=[[1,2,3],[4,5,6]]  

sess=tf.Session()  
begin_x=[1,0]        #第一个1，决定了从x的第二行[4,5,6]开始，第二个0，决定了从[4,5,6] 中的4开始抽取  
size_x=[1,2]           # 第一个1决定了，从第二行以起始位置抽取1行，也就是只抽取[4,5,6] 这一行，在这一行中从4开始抽取2个元素  
out=tf.slice(x,begin_x,size_x)  
print('x = {}'.format(x) )
print('x_slice = {}'.format(sess.run(out)) )
# print sess.run(out)  #  结果:[[4 5]]  
  
y=np.arange(24).reshape([2,3,4])  
begin_y=[1,0,0]  
size_y=[1,2,3]  
out=tf.slice(y,begin_y,size_y)     
print('y = {}'.format(y) )
print('y_slice = {}'.format(sess.run(out)) )
# print sess.run(out)  # 结果:[[[12 13 14] [16 17 18]]]  

# 1 
# z=tf.constant([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]],  [[13,14,15],[16,17,18]]]  )
# 2
z=np.arange(18).reshape([3,2,3])  


# Note: result of 1 & 2 is different, arange index from 0

begin_z=[0,1,1]  
size_z=[-1,1,2]   
out=tf.slice(z,begin_z,size_z)
print('z = {}'.format(z) )
print('z_slice = {}'.format(sess.run(out)) )
# print sess.run(out)  # size[i]=-1 表示第i维从begin[i]剩余的元素都要被抽取，结果：[[[ 5  6]] [[11 12]] [[17 18]]]  

x = [[1, 2, 3], [4, 5, 6]]
x_slice = [[4 5]]
y = [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
y_slice = [[[12 13 14]
  [16 17 18]]]
z = [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
z_slice = [[[ 4  5]]

 [[10 11]]

 [[16 17]]]


tf.unstack()
==========

In [2]:
#-----Test for unstack------#
import tensorflow as tf

A = [ [4,6, 5 ], 
      [2,2, 2],
     [0,0, 0 ],
     [4,4, 4 ],
     [5, 5, 5 ]
    ]

u = tf.unstack(A, axis = 0)
t = tf.unstack(A, axis = 1)
# Launch the graph
with tf.Session() as sess:
    print('u = ' + str( sess.run(u) ) )
    print('t = ' + str( sess.run(t) ) )
    

u = [array([4, 6, 5], dtype=int32), array([2, 2, 2], dtype=int32), array([0, 0, 0], dtype=int32), array([4, 4, 4], dtype=int32), array([5, 5, 5], dtype=int32)]
t = [array([4, 2, 0, 4, 5], dtype=int32), array([6, 2, 0, 4, 5], dtype=int32), array([5, 2, 0, 4, 5], dtype=int32)]


In [3]:
#-----Test for unstack------#
import tensorflow as tf

A = [  
      [ 
            [4,6, 5 ], 
            [2,2, 2] 
      ],
      [
         [0,0, 0 ],
         [4,4, 4 ]
         
      ],
      [
          [5, 5, 5 ],
          [6, 6, 6]
      ]
    ]

u = tf.unstack(A, 3)
# t = tf.unstack(A, 3, axis = 1)
# Launch the graph
with tf.Session() as sess:
    print('u = ' + str( sess.run(u) ) )
#     print('t = ' + str( sess.run(t) ) )
    

u = [array([[4, 6, 5],
       [2, 2, 2]], dtype=int32), array([[0, 0, 0],
       [4, 4, 4]], dtype=int32), array([[5, 5, 5],
       [6, 6, 6]], dtype=int32)]


# tf.random_normal()

In [ ]:
#-----Test for random_normal------#
import tensorflow as tf

in_size = 3
out_size = 7 
ran_norm = tf.random_normal([in_size, out_size])
                            
with tf.Session() as sess:
    print('ran_norm = ' + str( sess.run(ran_norm) ) )

# tf.one_hot()

In [1]:
#-----Test for unstack------#
import tensorflow as tf

NUM_ACTIONS = 4
action = 2

u = tf.one_hot(action, NUM_ACTIONS)

with tf.Session() as sess:
    print('u = ' + str( sess.run(u) ) )


u = [ 0.  0.  1.  0.]


# tf.range()

In [3]:
import tensorflow as tf

# tt = tf.range(start, limit, delta) 
tt = tf.range(0, 7, 3) 
tt_2 = tf.range(0, 7) 


with tf.Session() as sess:
    tt_res = sess.run(tt)
    print(tt_res)
    print  sess.run(tt_2)
    

[0 3 6]
[0 1 2 3 4 5 6]


# tf.Print()             exe only

In [8]:
# Initialize session
import tensorflow as tf
sess = tf.InteractiveSession()

# Some tensor we want to print the value of
a = tf.constant([1.0, 3.0])

# Add print operation
a = tf.Print(a, [a], message="This is a: ")

# Add more elements of the graph using a
b = tf.add(a, a).eval()

In [6]:
import tensorflow as tf

x_input_data = tf.random_normal([4], mean=-1, stddev=4)

x_input_data = tf.Print(x_input_data, data=[ x_input_data], message="x_input_data:")

final = x_input_data + 1

final = tf.Print(final, data=[ final], message="final:")

with tf.Session() as sess:
    print sess.run(final)

    

array([ 0.23377556,  5.40827465,  6.46472454, -2.60594249], dtype=float32)

# tf.gather()

![tf.gather()](https://www.tensorflow.org/images/Gather.png)

# tf.reduce_mean()

```
'x' is [[1., 1.]
         [2., 2.]]
         
tf.reduce_mean(x) ==> 1.5
tf.reduce_mean(x, 0) ==> [1.5, 1.5]
tf.reduce_mean(x, 1) ==> [1.,  2.]
```


# tf.clip_by_value(A, min, max)

tf.clip_by_value(A, min, max)：输入一个张量A，把A中的每一个元素的值都压缩在min和max之间。小于min的让它等于min，大于max的元素的值等于max。

In [2]:
import tensorflow as tf;  
import numpy as np;  
  
A = np.array([[1,1,2,4], [3,4,8,5]])  
  
with tf.Session() as sess:  
    print sess.run(tf.clip_by_value(A, 2, 5))  

[[2 2 2 4]
 [3 4 5 5]]
