In [14]:
import tensorflow as tf
import numpy as np


#---'input.shape', (1, 2, 2, 3) ---#
input = tf.constant([[
      [  [ 1.1,  1.1,  1.1],
         [ 1.2,  1.2,  1.2]  ],

      [  [ 2.1,  2.1,  2.1],
         [ 2.2,  2.2,  2.2]  ]
    ]])  

#---'filter.shape', (1, 1, 3, 1) ---#
filter = tf.constant([[
     [   [ 10.],  [10.],  [10.] ]
   ]])  
  
op = tf.nn.conv2d(input, filter, strides=[1, 1, 1, 1], padding='VALID')  


i = tf.Print(input,[input])

# Initializing the variables
init = tf.global_variables_initializer()

with tf.Session() as sess:
#     sess = tf.InteractiveSession()
    print sess.run(init)
#     print input
    
    i = sess.run(input)
    f = sess.run(filter)
    
    print('input.shape', i.shape,'input',i )
    print('filter.shape', f.shape,'filter',f)
    
    op_run = sess.run(op)
    print('op.shape= ' + str(op_run.shape))
    print('op ->')
    print(op_run)


None
('input.shape', (1, 2, 2, 3), 'input', array([[[[ 1.10000002,  1.10000002,  1.10000002],
         [ 1.20000005,  1.20000005,  1.20000005]],

        [[ 2.0999999 ,  2.0999999 ,  2.0999999 ],
         [ 2.20000005,  2.20000005,  2.20000005]]]], dtype=float32))
('filter.shape', (1, 1, 3, 1), 'filter', array([[[[ 10.],
         [ 10.],
         [ 10.]]]], dtype=float32))
op.shape= (1, 2, 2, 1)
op ->
[[[[ 33.]
   [ 36.]]

  [[ 63.]
   [ 66.]]]]
input ->
filter ->
[[[[ 10.]
   [ 10.]
   [ 10.]]]]


In [15]:
#----Test one-----#
import numpy as np
a = i[0][0][0]
print ('a' ,a)
print('a.shape = ' + str(a.shape) )

b = f[0][0]
print('b',b)
print('b.shape = ' + str(b.shape) )
axb = np.dot(a,b)
axb

('a', array([ 1.10000002,  1.10000002,  1.10000002], dtype=float32))
a.shape = (3,)
('b', array([[ 10.],
       [ 10.],
       [ 10.]], dtype=float32))
b.shape = (3, 1)


array([ 33.], dtype=float32)

In [16]:
#-----Test Getting Shape----#
i_shape =  i.shape
print i_shape      # ex (1, 3, 3, 5)
print i_shape[0]

batch = 0  # i[0]

for j in range(i_shape[1]):  # me, get tensor 1 dimension
    for k in range(i_shape[2]):
        a = i[batch][j][k]
        b = f[0][0]
        axb = np.dot(a,b)
        print axb
        
    print ''


(1, 2, 2, 3)
1
[ 33.]
[ 36.]

[ 63.]
[ 66.]



Test different(2*2) filter
===========

In [24]:
#------Test different(2*2) filter ------#

import tensorflow as tf

input = tf.Variable(tf.random_normal([1,3,3,5]))  
filter = tf.Variable(tf.random_normal([2,2,5,1]))  
  
#---'input.shape', (1, 2, 2, 3) ---#
input = tf.constant([[
      [  [ 1.1,  1.1,  1.1],
         [ 1.2,  1.2,  1.2]  ],

      [  [ 2.1,  2.1,  2.1],
         [ 2.2,  2.2,  2.2]  ]
    ]])  

# #---'filter.shape', (2, 2, 3, 1) ---#
filter = tf.constant(
[[[[10.],
   [10.],
   [10.]],

  [[20.],
   [20.],
   [20.]]],


 [[[30.],
   [30.],
   [30.]],

  [[40.],
   [40.],
   [40.]]]] )

# col1:  0 + 36 + 0 + 66*3 = 36+198 = 234
# col3:  2.2*10*3 = 66

# filter = tf.constant([[
#      [   [ 10.],  [10.],  [10.] ]
#    ]])      

# op = tf.nn.conv2d(input, filter, strides=[1, 1, 1, 1], padding='VALID')  
op = tf.nn.conv2d(input, filter, strides=[1, 1, 1, 1], padding='SAME')  



i = tf.Print(input,[input])

# Initializing the variables
init = tf.global_variables_initializer()

with tf.Session() as sess:
#     sess = tf.InteractiveSession()
    print sess.run(init)
#     print input
    
    op_run = sess.run(op)
    print('op.shape= ' + str(op_run.shape))
    print('op ->')
    print(op_run)
#     print i
    i = input.eval()
    print('input.shape',i.shape)
    print(i)
    
    f = filter.eval()
    print('filter.shape',f.shape)
    print(f)

None
op.shape= (1, 2, 2, 1)
op ->
[[[[ 558.]
   [ 234.]]

  [[ 195.]
   [  66.]]]]
('input.shape', (1, 2, 2, 3))
[[[[ 1.10000002  1.10000002  1.10000002]
   [ 1.20000005  1.20000005  1.20000005]]

  [[ 2.0999999   2.0999999   2.0999999 ]
   [ 2.20000005  2.20000005  2.20000005]]]]
('filter.shape', (2, 2, 3, 1))
[[[[ 10.]
   [ 10.]
   [ 10.]]

  [[ 20.]
   [ 20.]
   [ 20.]]]


 [[[ 30.]
   [ 30.]
   [ 30.]]

  [[ 40.]
   [ 40.]
   [ 40.]]]]


note of 2*2 filter 
======
use VALID -> output tensor  (1, 2, 2, 1)

use SAME -> output tensor  (1, 3, 3, 1)

In [52]:
#----Test one with 2*2 filter-----#
import numpy as np

print('i.shape = ' + str(i.shape) )

print('f.shape = ' + str(f.shape) )


f_shape = f.shape

#-----Test Getting Shape----#
# i_shape =  i.shape
# print i_shape      # ex (1, 3, 3, 5)
# print i_shape[0]

batch = 0  # i[0]

for j in range(i_shape[1]):  # me, get tensor 1 dimension
    for k in range(i_shape[2]):
        s = 0 #sum
        for x in range(f.shape[0]):
            if (j + x) >= i_shape[1]: 
                break
            for y in range(f.shape[1]):
                if (k + y) >= i_shape[2]: 
                    break
#                 print('j+x = '+ str(j+x) )
#                 print('k+y = '+ str(k+y) )
                
                a = i[batch][j+x][k+y]
                b = f[x][y]
                axb = np.dot(a,b)
#                 print('axb = ' + str(axb)) 
                s = s + axb                #  important ------   multiply filter and add toghter
                
#         print('s  ----> ')
        print s
                
        
    print ''

i.shape = (1, 3, 3, 5)
f.shape = (2, 2, 5, 1)
[ 10.91066742]
[ 6.53901243]
[-7.46039772]

[ 1.77062333]
[ 1.95030677]
[ 3.1612606]

[-1.58539152]
[-3.70772552]
[ 1.1700902]



In [ ]:
#---For Record Test Data----#
[[[[ 10.91066742]
   [  6.53901196]
   [ -7.46039772]]

  [[  1.77062321]
   [  1.95030713]
   [  3.1612606 ]]

  [[ -1.58539128]
   [ -3.70772552]
   [  1.1700902 ]]]]

Test With Differnt Out Channel
=======

In [9]:
#----Test With Differnt Out Channel------# 
import tensorflow as tf

input = tf.Variable(tf.random_normal([1,3,3,5]))  
filter = tf.Variable(tf.random_normal([1,1,5,2]))  
  
op = tf.nn.conv2d(input, filter, strides=[1, 1, 1, 1], padding='VALID')  


i = tf.Print(input,[input])

# Initializing the variables
init = tf.global_variables_initializer()

with tf.Session() as sess:
#     sess = tf.InteractiveSession()
    print sess.run(init)
#     print input
    
    op_run = sess.run(op)
    print('op.shape= ' + str(op_run.shape))
    print('op ->')
    print(op_run)
#     print i
    i = input.eval()
    print('input ->')
    print(i)
    
    f = filter.eval()
    print('filter: ' + str(f.shape) +' ->')
    print(f)

None
op.shape= (1, 3, 3, 2)
op ->
[[[[  2.72437859e+00   8.77986372e-01]
   [  5.79973698e-01  -7.76740670e-01]
   [ -2.86222219e-01   4.07304287e+00]]

  [[  1.99107134e+00  -2.99000740e-03]
   [ -1.44519198e+00   5.54613352e-01]
   [  2.05971241e+00  -5.29438066e+00]]

  [[ -2.08342075e+00  -9.88741398e-01]
   [ -9.26128149e-01  -2.17836452e+00]
   [  2.58143640e+00  -2.07778364e-01]]]]
input ->
[[[[ 1.28437507  0.40533164  0.20954601  0.06123202  0.01398064]
   [ 0.1298566   0.95475525 -1.07261825  0.213752    0.49422541]
   [ 0.22992861  0.23334277  1.13666773  0.48275319  1.4979527 ]]

  [[ 0.84717822  0.47890055 -0.34139735  0.52007073  0.63943785]
   [-0.49053946 -1.22950566  0.28296405 -2.13096666 -0.93342334]
   [ 0.40095899 -0.08465092 -1.76012421  0.44305348 -0.60504675]]

  [[-1.11284256  0.7777791  -1.43619978  1.02875304  1.9085685 ]
   [-0.63494372  0.35268399 -0.65871185  0.33375522 -0.61986142]
   [ 1.12738216  0.34613401 -1.1760726  -1.26324725  0.29619285]]]]
filter:

In [70]:
#----Test one With Differnt Out Channel-----#
import numpy as np
a = i[0][0][0]
print('a = ' + str(a))
print('a.shape = ' + str(a.shape) )

b = f[0,0,:,0]
print('f[0,0,:,0] = ' + str(b))
print('b.shape = ' + str(b.shape) )
axb_00 = np.dot(a,b)
print axb_00

b = f[0,0,:,1]
print('f[0,0,:,1] = ' + str(b))
print('b.shape = ' + str(b.shape) )
axb_01 = np.dot(a,b)
print axb_01


print('Result of [0,0] & [0,1] ')
print('[ ' + str(axb_00) + ', ' +  str(axb_01) +'] --->  same as convolution colum 0')


a = [-0.99288738 -1.9496783  -0.06509738 -0.44621241 -1.9109093 ]
a.shape = (5,)
f[0,0,:,0] = [ 0.25707984  2.52177858 -0.435913    1.61234844  0.44589883]
b.shape = (5,)
-6.71505
f[0,0,:,1] = [ 0.42749092  0.8745597  -0.84834802  3.32428122  0.23526999]
b.shape = (5,)
-4.00725
Result of [0,0] & [0,1] 
[ -6.71505,-4.00725] --->  same as convolution colum 0


tf.contrib.layers.conv2d
============

First, Known tf.constant_initializer() 

In [68]:
#--------Known tf.constant_initializer()-------#
# from: https://www.tensorflow.org/api_docs/python/tf/constant_initializer
import numpy as np
import tensorflow as tf

value = [0, 1, 2, 3, 4, 5, 6, 7]
# value = np.array(value)
# value = value.reshape([2, 4])
init = tf.constant_initializer(value)

print('fitting shape:')
with tf.Session():
    x = tf.get_variable('y1', shape=[2, 4], initializer=init)
    x.initializer.run()
    print(x.eval())

#   fitting shape:
#   [[ 0.  1.  2.  3.]
#    [ 4.  5.  6.  7.]]

print('larger shape:')
with tf.Session():
    x = tf.get_variable('y2', shape=[3, 4], initializer=init)
    x.initializer.run()
    print(x.eval())

#   larger shape:
#   [[ 0.  1.  2.  3.]
#    [ 4.  5.  6.  7.]
#    [ 7.  7.  7.  7.]]

# print('smaller shape:')
# with tf.Session():
#     x = tf.get_variable('x3', shape=[2, 3], initializer=init)

fitting shape:
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]]
larger shape:
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 7.  7.  7.  7.]]


In [78]:
import tensorflow as tf


#---'input.shape', (1, 2, 2, 3) ---#
input = tf.constant([[
      [  [ 1.1,  1.1,  1.1],
         [ 1.2,  1.2,  1.2]  ],

      [  [ -2.1,  -2.1,  -2.1],
         [ 2.2,  2.2,  2.2]  ]
    ]])  


conv1_1 = np.random.rand(1, 1, 3, 1).astype(np.float32)
#---'filter.shape', (1, 1, 3, 1) ---#
# origin in tf.nn.conv2d
filter = tf.constant([[
     [   [ 10.],  [10.],  [10.] ]
   ]])  

value = [10,10,10]
init = tf.constant_initializer(value)


conv2d = tf.contrib.layers.conv2d(
    input,
    num_outputs=1,
    weights_initializer=init, # x,  # tf.constant_initializer(0),  -> (OK)
    kernel_size=(1,1),          # It's only the filter height and width.
#     activation_fn=tf.nn.relu, tf.nn.relu is default
#     stride=(1, 1),              # Skips the stride values for image_batch and input_channels.
    trainable=True)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    c2d = sess.run(conv2d)
    print('conv2d--->', ' shape', c2d.shape)
    print(c2d)
#     img = image_input.eval()
#     print('img.shape',img.shape)

('conv2d--->', ' shape', (1, 2, 2, 1))
[[[[ 33.]
   [ 36.]]

  [[  0.]
   [ 66.]]]]


tf.contrib.layers.conv2d ()   & Get Weight & Bias
===========
conv2d(
    inputs,
    filters,
    kernel_size,
    strides=(1, 1),
    padding='valid',
    data_format='channels_last',
    dilation_rate=(1, 1),
    activation=None,
    use_bias=True,
    kernel_initializer=None,
    bias_initializer=tf.zeros_initializer(),
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    trainable=True,
    name=None,
    reuse=None
)


In [123]:
import tensorflow as tf


tf.reset_default_graph()    # reset all variables
#---'input.shape', (1, 2, 2, 3) ---#
input = tf.constant([[
      [  [ 1.1,  1.1,  1.1],
         [ 1.2,  1.2,  1.2]  ],

      [  [ 2.1,  2.1,  2.1],
         [ 2.2,  2.2,  2.2]  ]
    ]])  


#---'filter.shape', (1, 1, 3, 1) ---#
# origin in tf.nn.conv2d
filter = tf.constant([[
     [   [ 10.],  [10.],  [10.] ]
   ]])  

value = [10,10,10]
init = tf.constant_initializer(value)


tmp_name= 'conv1'

conv2d_f_1 = tf.layers.conv2d(
    input,
    filters=1,  # output
    kernel_initializer=init, # x,  # tf.constant_initializer(0),  -> (OK)
    kernel_size=(1,1),          # It's only the filter height and width.
#     activation_fn=tf.nn.relu, # tf.nn.relu is default
    trainable=True,
    name=tmp_name)


with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    c2d = sess.run(conv2d_f_1)
    print('conv2d--->', ' shape', c2d.shape)
    print(c2d)
    
    variables_names =[v.name for v in tf.trainable_variables() ]  # see all trainable_variables
#     variables_names =[v.name for v in tf.trainable_variables() if tmp_name in v.name]  # see want layers
    values = sess.run(variables_names) 
    for k,v in zip(variables_names, values):
        print(k, v)


('conv2d--->', ' shape', (1, 2, 2, 2))
[[[[ 33.  33.]
   [ 36.  36.]]

  [[ 63.  63.]
   [ 66.  66.]]]]
(u'conv1/kernel:0', array([[[[ 10.,  10.],
         [ 10.,  10.],
         [ 10.,  10.]]]], dtype=float32))
(u'conv1/bias:0', array([ 0.,  0.], dtype=float32))


tf."contrib".layers.conv2d () Try Different "filters"
=======
conv2d(

    inputs,
    
    num_outputs,
    
    kernel_size,
    
    stride=1,
    padding='SAME',
    data_format=None,
    rate=1,
    activation_fn=tf.nn.relu,
    normalizer_fn=None,
    normalizer_params=None,
    weights_initializer=initializers.xavier_initializer(),
    weights_regularizer=None,
    biases_initializer=tf.zeros_initializer(),
    biases_regularizer=None,
    reuse=None,
    variables_collections=None,
    outputs_collections=None,
    trainable=True,
    scope=None
)

In [130]:
import tensorflow as tf


tf.reset_default_graph()    # reset all variables
#---'input.shape', (1, 2, 2, 3) ---#
input = tf.constant([[
      [  [ 1.1,  1.1,  1.1],
         [ 1.2,  1.2,  1.2]  ],

      [  [ 2.1,  2.1,  2.1],
         [ 2.2,  2.2,  2.2]  ]
    ]])  


#---'filter.shape', (1, 1, 3, 1) ---#
# origin in tf.nn.conv2d
filter = tf.constant([[
     [   [ 10.],  [10.],  [10.] ]
   ]])  

value = [10,10,10]
init = tf.constant_initializer(value)


tmp_name= 'conv11'

conv2d_f_1 = tf.layers.conv2d(
    input,
    filters=1,  # output
    kernel_initializer=init, # x,  # tf.constant_initializer(0),  -> (OK)
    kernel_size=(1,1),          # It's only the filter height and width.
#     activation_fn=tf.nn.relu, # tf.nn.relu is default
    trainable=True,
    name='conv_f_1')

conv2d_f_2 = tf.layers.conv2d(
    input,
    filters=2,  # output
    kernel_initializer=init, # x,  # tf.constant_initializer(0),  -> (OK)
    kernel_size=(1,1),          # It's only the filter height and width.
#     activation_fn=tf.nn.relu, # tf.nn.relu is default
    trainable=True,
    name='conv_f_2')


with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    c2d = sess.run(conv2d_f_1)
    print('conv2d_f_1--->', ' shape', c2d.shape)
    print(c2d)
    
    
    c2d = sess.run(conv2d_f_2)
    print('conv2d_f_2--->', ' shape', c2d.shape)
    print(c2d)
    


('conv2d_f_1--->', ' shape', (1, 2, 2, 1))
[[[[ 33.]
   [ 36.]]

  [[ 63.]
   [ 66.]]]]
('conv2d_f_2--->', ' shape', (1, 2, 2, 2))
[[[[ 33.  33.]
   [ 36.  36.]]

  [[ 63.  63.]
   [ 66.  66.]]]]


tf.contrib.layers.conv2d () ->  Try Different "kernel_size"
=======

In [142]:
### import tensorflow as tf


tf.reset_default_graph()    # reset all variables
#---'input.shape', (1, 2, 2, 3) ---#
input = tf.constant([[
      [  [ 1.1,  1.1,  1.1],
         [ 1.2,  1.2,  1.2]  ],

      [  [ 2.1,  2.1,  2.1],
         [ 2.2,  2.2,  2.2]  ]
    ]])  


#---'filter.shape', (1, 1, 3, 1) ---#
# origin in tf.nn.conv2d
filter = tf.constant([[
     [   [ 30.],  [20.],  [10.] ]
   ]])  

value = [30,20,10]
init = tf.constant_initializer(value)


tmp_name= 'conv11'


# filter shape be (2, 2, 3, 1)
conv2d_k_2_2 = tf.layers.conv2d(
    input,
    filters=1,  # output
    kernel_initializer=init, # x,  # tf.constant_initializer(0),  -> (OK)
    kernel_size=(2,2),          # It's only the filter height and width.
#     activation_fn=tf.nn.relu, # tf.nn.relu is default
    trainable=True,
    name='conv2d_k_2_2')

#  (1.1*10+1.1*20+1.1*30) + 1.2*10*3 +  2.1*10*3 +  2.2*10*3
# = (11+22+33) + 36+63+66
# = 66 + 36 + 63 + 66
# = 231

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    c2d = sess.run(conv2d_k_2_2)
    print('conv2d_k_2_2--->', ' shape', c2d.shape)
    print(c2d)
    
    variables_names =[v.name for v in tf.trainable_variables() ]  # see all trainable_variables
#     variables_names =[v.name for v in tf.trainable_variables() if tmp_name in v.name]  # see want layers
    values = sess.run(variables_names) 
    for k,v in zip(variables_names, values):
        print(k, 'Shape:' + str(v.shape), v)



('conv2d_k_2_2--->', ' shape', (1, 1, 1, 1))
[[[[ 231.]]]]
(u'conv2d_k_2_2/kernel:0', 'Shape:(2, 2, 3, 1)', array([[[[ 30.],
         [ 20.],
         [ 10.]],

        [[ 10.],
         [ 10.],
         [ 10.]]],


       [[[ 10.],
         [ 10.],
         [ 10.]],

        [[ 10.],
         [ 10.],
         [ 10.]]]], dtype=float32))
(u'conv2d_k_2_2/bias:0', 'Shape:(1,)', array([ 0.], dtype=float32))
