In [55]:
import tensorflow as tf

input = tf.Variable(tf.random_normal([1,3,3,5]))  
filter = tf.Variable(tf.random_normal([1,1,5,1]))  
  
op = tf.nn.conv2d(input, filter, strides=[1, 1, 1, 1], padding='VALID')  


i = tf.Print(input,[input])

# Initializing the variables
init = tf.global_variables_initializer()

with tf.Session() as sess:
#     sess = tf.InteractiveSession()
    print sess.run(init)
#     print input
    
    op_run = sess.run(op)
    print('op.shape= ' + str(op_run.shape))
    print('op ->')
    print(op_run)
#     print i
    i = input.eval()
    print('input ->')
    print(v)
    
    f = filter.eval()
    print('filter ->')
    print(f)

None
op.shape= (1, 3, 3, 1)
op ->
[[[[-1.47482526]
   [-0.41506335]
   [ 0.1682024 ]]

  [[-0.81600702]
   [-0.46789187]
   [-0.40545577]]

  [[ 0.15955564]
   [ 1.28365827]
   [ 0.63668406]]]]
input ->
[[[[ 0.18354212  0.04310609 -1.69357932  2.52137446  0.81831217]
   [-0.65873384  0.734909    0.57711357 -0.09049443 -0.22313042]
   [ 0.12068126 -0.54358184 -0.40195572  0.01604476 -1.00850964]]

  [[ 0.11884379  0.64390957 -0.79883766  0.09010001  0.78838235]
   [ 1.32106543  1.33582389 -1.1764437   0.92073876 -0.52782893]
   [-0.29765347 -0.21230677 -0.97579432  1.96770442  0.36002848]]

  [[ 1.66000569 -0.06999575 -0.72257751  0.12685859  1.30449867]
   [-0.05592554 -0.03374482  0.42967561  0.13802923  0.39743382]
   [-1.51017606  0.76810801 -1.20949721 -0.5777657   0.27024782]]]]
filter ->
[[[[-0.62746519]
   [-0.09532461]
   [ 0.47764039]
   [-0.11251568]
   [ 0.24137871]]]]


In [36]:
#----Test one-----#
import numpy as np
a = i[0][0][0]
print a
print('a.shape = ' + str(a.shape) )

b = f[0][0]
print b
print('b.shape = ' + str(b.shape) )
axb = np.dot(a,b)
axb

[-0.84149295 -0.65499955  0.6487695  -0.93239361  0.33005363]
a.shape = (5,)
[[-1.01911473]
 [-0.72998601]
 [ 0.79135501]
 [ 0.44278196]
 [ 0.47078079]]
b.shape = (5, 1)


array([ 1.59166121], dtype=float32)

In [38]:
#-----Test Getting Shape----#
i_shape =  i.shape
print i_shape      # ex (1, 3, 3, 5)
print i_shape[0]

batch = 0  # i[0]

for j in range(i_shape[1]):  # me, get tensor 1 dimension
    for k in range(i_shape[2]):
        a = i[batch][j][k]
        b = f[0][0]
        axb = np.dot(a,b)
        print axb
        
    print ''


(1, 3, 3, 5)
1
[ 1.59166121]
[ 1.96764302]
[ 1.30719566]

[ 0.41158086]
[ 1.29665637]
[-0.29811031]

[-4.5670476]
[ 2.44930339]
[-1.19264483]



Test different(2*2) filter
===========

In [6]:
#------Test different(2*2) filter ------#

import tensorflow as tf

input = tf.Variable(tf.random_normal([1,3,3,5]))  
filter = tf.Variable(tf.random_normal([2,2,5,1]))  
  
# op = tf.nn.conv2d(input, filter, strides=[1, 1, 1, 1], padding='VALID')  
op = tf.nn.conv2d(input, filter, strides=[1, 1, 1, 1], padding='SAME')  



i = tf.Print(input,[input])

# Initializing the variables
init = tf.global_variables_initializer()

with tf.Session() as sess:
#     sess = tf.InteractiveSession()
    print sess.run(init)
#     print input
    
    op_run = sess.run(op)
    print('op.shape= ' + str(op_run.shape))
    print('op ->')
    print(op_run)
#     print i
    i = input.eval()
    print('input ->')
    print(i)
    
    f = filter.eval()
    print('filter ->')
    print(f)

None
op.shape= (1, 4, 4, 1)
op ->
[[[[-1.10804176]
   [-0.72836936]
   [-3.32222509]
   [ 0.73050916]]

  [[-1.09239078]
   [-3.97197127]
   [-1.91689098]
   [-3.11569691]]

  [[-6.5242815 ]
   [-2.04061031]
   [-0.83294749]
   [-1.86441231]]

  [[-3.46149611]
   [-2.06166196]
   [-0.84477818]
   [-0.21588326]]]]
input ->
[[[[ 0.74987453 -0.93930149  0.09991658  1.02164769  1.17628443]
   [ 0.3578912   1.37779117  0.13016453 -0.96194756 -1.27554047]
   [-0.1268917   0.85930574  1.98556554  0.82816905 -0.46493527]
   [-1.08283758 -0.93318164 -1.11811066 -1.04505193 -0.39139229]]

  [[-0.98069078  0.81567633 -1.01965773  0.7824142  -0.40045723]
   [ 2.41978312 -0.28815955  1.45403504 -0.93779385  0.91394997]
   [ 0.4143227   0.04495757 -0.54551661  0.89277053 -1.12244761]
   [ 0.24115278  1.12178433  0.66101968 -0.41907901 -1.38993537]]

  [[-0.66793984  0.00721651  0.21818852 -2.00269485  0.14369453]
   [ 0.63453841  0.10181987 -1.36363268 -1.87375915  0.11832476]
   [ 0.57917941  0.797

note of 2*2 filter 
======
use VALID -> output tensor  (1, 2, 2, 1)

use SAME -> output tensor  (1, 3, 3, 1)

In [52]:
#----Test one with 2*2 filter-----#
import numpy as np

print('i.shape = ' + str(i.shape) )

print('f.shape = ' + str(f.shape) )


f_shape = f.shape

#-----Test Getting Shape----#
# i_shape =  i.shape
# print i_shape      # ex (1, 3, 3, 5)
# print i_shape[0]

batch = 0  # i[0]

for j in range(i_shape[1]):  # me, get tensor 1 dimension
    for k in range(i_shape[2]):
        s = 0 #sum
        for x in range(f.shape[0]):
            if (j + x) >= i_shape[1]: 
                break
            for y in range(f.shape[1]):
                if (k + y) >= i_shape[2]: 
                    break
#                 print('j+x = '+ str(j+x) )
#                 print('k+y = '+ str(k+y) )
                
                a = i[batch][j+x][k+y]
                b = f[x][y]
                axb = np.dot(a,b)
#                 print('axb = ' + str(axb)) 
                s = s + axb                #  important ------   multiply filter and add toghter
                
#         print('s  ----> ')
        print s
                
        
    print ''

i.shape = (1, 3, 3, 5)
f.shape = (2, 2, 5, 1)
[ 10.91066742]
[ 6.53901243]
[-7.46039772]

[ 1.77062333]
[ 1.95030677]
[ 3.1612606]

[-1.58539152]
[-3.70772552]
[ 1.1700902]



In [ ]:
#---For Record Test Data----#
[[[[ 10.91066742]
   [  6.53901196]
   [ -7.46039772]]

  [[  1.77062321]
   [  1.95030713]
   [  3.1612606 ]]

  [[ -1.58539128]
   [ -3.70772552]
   [  1.1700902 ]]]]

Test With Differnt Out Channel
=======

In [9]:
#----Test With Differnt Out Channel------# 
import tensorflow as tf

input = tf.Variable(tf.random_normal([1,3,3,5]))  
filter = tf.Variable(tf.random_normal([1,1,5,2]))  
  
op = tf.nn.conv2d(input, filter, strides=[1, 1, 1, 1], padding='VALID')  


i = tf.Print(input,[input])

# Initializing the variables
init = tf.global_variables_initializer()

with tf.Session() as sess:
#     sess = tf.InteractiveSession()
    print sess.run(init)
#     print input
    
    op_run = sess.run(op)
    print('op.shape= ' + str(op_run.shape))
    print('op ->')
    print(op_run)
#     print i
    i = input.eval()
    print('input ->')
    print(i)
    
    f = filter.eval()
    print('filter: ' + str(f.shape) +' ->')
    print(f)

None
op.shape= (1, 3, 3, 2)
op ->
[[[[  2.72437859e+00   8.77986372e-01]
   [  5.79973698e-01  -7.76740670e-01]
   [ -2.86222219e-01   4.07304287e+00]]

  [[  1.99107134e+00  -2.99000740e-03]
   [ -1.44519198e+00   5.54613352e-01]
   [  2.05971241e+00  -5.29438066e+00]]

  [[ -2.08342075e+00  -9.88741398e-01]
   [ -9.26128149e-01  -2.17836452e+00]
   [  2.58143640e+00  -2.07778364e-01]]]]
input ->
[[[[ 1.28437507  0.40533164  0.20954601  0.06123202  0.01398064]
   [ 0.1298566   0.95475525 -1.07261825  0.213752    0.49422541]
   [ 0.22992861  0.23334277  1.13666773  0.48275319  1.4979527 ]]

  [[ 0.84717822  0.47890055 -0.34139735  0.52007073  0.63943785]
   [-0.49053946 -1.22950566  0.28296405 -2.13096666 -0.93342334]
   [ 0.40095899 -0.08465092 -1.76012421  0.44305348 -0.60504675]]

  [[-1.11284256  0.7777791  -1.43619978  1.02875304  1.9085685 ]
   [-0.63494372  0.35268399 -0.65871185  0.33375522 -0.61986142]
   [ 1.12738216  0.34613401 -1.1760726  -1.26324725  0.29619285]]]]
filter:

In [70]:
#----Test one With Differnt Out Channel-----#
import numpy as np
a = i[0][0][0]
print('a = ' + str(a))
print('a.shape = ' + str(a.shape) )

b = f[0,0,:,0]
print('f[0,0,:,0] = ' + str(b))
print('b.shape = ' + str(b.shape) )
axb_00 = np.dot(a,b)
print axb_00

b = f[0,0,:,1]
print('f[0,0,:,1] = ' + str(b))
print('b.shape = ' + str(b.shape) )
axb_01 = np.dot(a,b)
print axb_01


print('Result of [0,0] & [0,1] ')
print('[ ' + str(axb_00) + ', ' +  str(axb_01) +'] --->  same as convolution colum 0')


a = [-0.99288738 -1.9496783  -0.06509738 -0.44621241 -1.9109093 ]
a.shape = (5,)
f[0,0,:,0] = [ 0.25707984  2.52177858 -0.435913    1.61234844  0.44589883]
b.shape = (5,)
-6.71505
f[0,0,:,1] = [ 0.42749092  0.8745597  -0.84834802  3.32428122  0.23526999]
b.shape = (5,)
-4.00725
Result of [0,0] & [0,1] 
[ -6.71505,-4.00725] --->  same as convolution colum 0
