In [2]:
import numpy as np




epsilon_start=1.0
epsilon_end=0.1
epsilon_decay_steps=500000

epsilons = np.linspace(epsilon_start, epsilon_end, epsilon_decay_steps)

print('epsilons.shape',epsilons.shape)
print(epsilons)

('epsilons.shape', (500000,))
[ 1.         0.9999982  0.9999964 ...,  0.1000036  0.1000018  0.1      ]


ZIP
=========

In [4]:
a = [1,2,3]
b = [4,5,6]

zipped = zip(a,b)

print(zipped)


print(zip(a,c))

print(zip(*zipped))

[(1, 4), (2, 5), (3, 6)]
[(1, 4), (2, 5), (3, 6)]
[(1, 2, 3), (4, 5, 6)]


ZIP (二維矩陣變換（矩陣的行列互換） )    & 與 map() 的結合
========

In [9]:
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print('zip(*a)')
print((zip(*a)) )
print('')

print('map(list,zip(*a))')
print(map(list,zip(*a)) )
print('')


print('map(np.array, zip(*a))')
print(map(np.array, zip(*a)))




zip(*a)
[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

map(list,zip(*a))
[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

map(np.array, zip(*a))
[array([1, 4, 7]), array([2, 5, 8]), array([3, 6, 9])]


namedtuple
==========

In [15]:
from collections import deque, namedtuple

# Transition = namedtuple("Transition", ["state", "action", "reward", "next_state", "done"])
Point = namedtuple('Point', ['x', 'y'])
print('Point.__doc__', Point.__doc__)                   # docstring for the new class

p = Point(11, y=22)             # instantiate with positional args or keywords
print('after Point(11, y=22) p[0] + p[1] =', p[0] + p[1])
# print(p[0] + p[1])                     # indexable like a plain tuple

x, y = p                        # unpack like a regular tuple
print('x, y = p ','x = ' + str(x) , 'y = ' + str(y))


print('p.x + p.y = ' + str(p.x + p.y) )                     # fields also accessible by name

d = p._asdict()                 # convert to a dictionary
print('d = p._asdict() =',  d)
print('d[\'x\']', d['x'])

print('Point(**d) = ' , Point(**d))                     # convert from a dictionary
# Point(x=11, y=22)

print('p._replace(x=100) =', p._replace(x=100) )               # _replace() is like str.replace() but targets named fields


('Point.__doc__', 'Point(x, y)')
('after Point(11, y=22) p[0] + p[1] =', 33)
('x, y = p ', 'x = 11', 'y = 22')
p.x + p.y = 33
('d = p._asdict() =', OrderedDict([('x', 11), ('y', 22)]))
("d['x']", 11)
('Point(**d) = ', Point(x=11, y=22))
('p._replace(x=100) =', Point(x=100, y=22))


np.stack
============

In [3]:
import numpy as np

arrays = [np.random.randn(13, 4) for _ in range(10)]
# print(arrays)
print(np.array( arrays).shape ) 
# print('arrays.shape', arrays.shape)
print('np.stack(arrays, axis=0).shape',np.stack(arrays, axis=0).shape)
print('np.stack(arrays, axis=1).shape',np.stack(arrays, axis=1).shape)
print('np.stack(arrays, axis=2).shape',np.stack(arrays, axis=2).shape)

print('np.stack(arrays, axis=-1).shape',np.stack(arrays, axis=-1).shape)

(10, 13, 4)
('np.stack(arrays, axis=0).shape', (10, 13, 4))
('np.stack(arrays, axis=1).shape', (13, 10, 4))
('np.stack(arrays, axis=2).shape', (13, 4, 10))
('np.stack(arrays, axis=-1).shape', (13, 4, 10))


In [29]:
arrays = [np.random.randn(3) for _ in range(5)]  # (5,3)
print(arrays)
# print('arrays.shape',arrays.shape)

state = np.stack([arrays] * 4, axis=2)  # copy same 

print(state)
print('state.shape',state.shape)


print('')
print('state[:,:,1:]')
print(state[:,:,1:])

[array([-1.06846326,  0.11353627,  0.35983055]), array([-0.33752517, -0.35191301,  0.7613503 ]), array([ 0.20681952, -0.49268125, -0.39007595]), array([ 0.10873263, -0.0653531 ,  1.06006128]), array([-0.09082631, -0.60585293,  0.19136584])]
[[[-1.06846326 -1.06846326 -1.06846326 -1.06846326]
  [ 0.11353627  0.11353627  0.11353627  0.11353627]
  [ 0.35983055  0.35983055  0.35983055  0.35983055]]

 [[-0.33752517 -0.33752517 -0.33752517 -0.33752517]
  [-0.35191301 -0.35191301 -0.35191301 -0.35191301]
  [ 0.7613503   0.7613503   0.7613503   0.7613503 ]]

 [[ 0.20681952  0.20681952  0.20681952  0.20681952]
  [-0.49268125 -0.49268125 -0.49268125 -0.49268125]
  [-0.39007595 -0.39007595 -0.39007595 -0.39007595]]

 [[ 0.10873263  0.10873263  0.10873263  0.10873263]
  [-0.0653531  -0.0653531  -0.0653531  -0.0653531 ]
  [ 1.06006128  1.06006128  1.06006128  1.06006128]]

 [[-0.09082631 -0.09082631 -0.09082631 -0.09082631]
  [-0.60585293 -0.60585293 -0.60585293 -0.60585293]
  [ 0.19136584  0.19136

In [39]:
next_state = np.array([ [1,2],
               [3,4]
                  ] )
print('next_state.shape',next_state.shape)
expand_2 = np.expand_dims(next_state, 2)   
print('expand_2')
print(expand_2)
print('expand_2.shape',expand_2.shape)

expand_1 = np.expand_dims(next_state, 1)   
print('expand_1')
print(expand_1)
print('expand_1.shape',expand_1.shape)

('next_state.shape', (2, 2))
expand_2
[[[1]
  [2]]

 [[3]
  [4]]]
('expand_2.shape', (2, 2, 1))
expand_1
[[[1 2]]

 [[3 4]]]
('expand_1.shape', (2, 1, 2))


next_state = np.append(state[:,:,1:], np.expand_dims(next_state, 2), axis=2)
======

In [47]:
state = [ [3,3] for _ in range(2)]  # (5,3)
print('ORI state', state)

state = np.stack([state] * 4, axis=2)  # copy same 
print('np.stack([state] * 4, axis=2) ')
print(state)
print('state.shape',state.shape)

# try to know next_state = np.append(state[:,:,1:], np.expand_dims(next_state, 2), axis=2)
next_state = np.array([ [1,2],
               [3,4]
                  ] )
next_state = np.append(state[:,:,1:], np.expand_dims(next_state, 2), axis=2)
print('next_state')
print(next_state)

('ORI state', [[3, 3], [3, 3]])
np.stack([state] * 4, axis=2) 
[[[3 3 3 3]
  [3 3 3 3]]

 [[3 3 3 3]
  [3 3 3 3]]]
('state.shape', (2, 2, 4))
next_state
[[[3 3 3 1]
  [3 3 3 2]]

 [[3 3 3 3]
  [3 3 3 4]]]


In [53]:
import random

arrays = [np.random.randn(3) for _ in range(5)]  # (5,3)
print('arrays')
print(arrays)

samples = random.sample(arrays, 2)
print('samples')
print(samples)

arrays
[array([ 0.10332675, -0.39308653,  0.52306322]), array([ 1.41298933, -1.12771569, -0.36654625]), array([ 1.44378993,  1.15437619,  0.60048043]), array([ 1.47666326, -1.26840043, -0.68958152]), array([-0.28919945,  0.96959523,  0.4999677 ])]
samples
[array([ 0.10332675, -0.39308653,  0.52306322]), array([ 1.47666326, -1.26840043, -0.68958152])]


# np.zero_like()

## Example 1

```
>>> x = np.arange(6)
>>> x = x.reshape((2, 3))
>>> x

array([[0, 1, 2],
       [3, 4, 5]])
       
>>> np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])
```
## Example 2:
```
>>> y = np.arange(3, dtype=np.float)
>>> y
array([ 0.,  1.,  2.])

>>> np.zeros_like(y)

array([ 0.,  0.,  0.])
```


# xrange()
所以xrange跟range最大的差別就是：
1. range 是全部產生完後，return一個 list 回來使用。
2. xrange 是一次產生一個值，並return一個值回來，所以xrange只適用於loop。
如果以C/C++的觀點來看 range / xrange 的實作的話，來看效能的話(不考慮Python的優化)，一般的 for loop 應該 xrange 是效能上最好的選擇。因為 range 多了 allocate array 跟 initialize 的動作。

refer: http://falldog7.blogspot.tw/2009/07/python-range-xrange.html

# np.prod() 
## return the product of array elements over a given axis.

Refer: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.prod.html

```
>>> np.prod([[1.,2.],[3.,4.]])
24.0

>>> np.prod([[1.,2.],[3.,4.]], axis=1)
array([  2.,  12.])

```