In [1]:
#-----Test for reduce_sum------#
import tensorflow as tf
# 'x' is [[1, 1, 1]
#         [1, 1, 1]]
# x = tf.constant([[1, 1, 1],
#                        [1, 1, 1]])

x = tf.constant([[1,1],
                 [2,2]])
a = tf.reduce_sum(x) 
b = tf.reduce_sum(x, 0) 
c = tf.reduce_sum(x, 1) 

print('a='+str(a))
with tf.Session() as sess:
    print 'a = ' + str(sess.run(a))
    print 'b = ' + str(sess.run(b))
    print 'c = ' + str(sess.run(c))

a=Tensor("Sum:0", shape=(), dtype=int32)
a = 6
b = [3 3]
c = [2 4]


In [5]:
#-----Test for reduce_sum------#
A = [ [
        [4,6, 5 ], 
        [2,2, 2]
      ],
      [
        [0,0, 0 ],
        [4,4, 4 ] 
      ]
]

a = tf.reduce_sum(A, 0) 
b = tf.reduce_sum(A, 1) 

print('a='+str(a))
with tf.Session() as sess:
    print 'a = ' + str(sess.run(a))
    print 'b = ' + str(sess.run(b))


a=Tensor("Sum:0", shape=(2, 3), dtype=int32)
a = [[4 6 5]
 [6 6 6]]
b = [[6 8 7]
 [4 4 4]]


In [10]:
#-----Test for nearest_neighbor------#
A = [ [4,6, 5 ], [2,2, 2],[0,0, 0 ],[4,4, 4 ],[5, 5, 5 ]]
A_Label = [1, 2, 3, 4, 5]
B = [ [1,1, 1 ]]



# tf Graph Input
xtr = tf.placeholder("float", [None, 3])
xte = tf.placeholder("float", [3])

# Nearest Neighbor calculation using L1 Distance
# Calculate L1 Distance
distance = tf.reduce_sum(tf.abs(tf.add(xtr, tf.negative(xte))), reduction_indices=1)
#dis = [  0.   3.   6.   9.  12.]

# Prediction: Get min distance index (Nearest neighbor)
pred = tf.arg_min(distance, 0)

accuracy = 0.

# Initializing the variables
init = tf.global_variables_initializer()

# Launch the graph
with tf.Session() as sess:
    sess.run(init)

    dis = sess.run(distance, feed_dict={xtr: A, xte: B[0]})
    print('dis = '+ str(dis))
    
    pred = sess.run(pred, feed_dict={xtr: A, xte: B[0]})
    print('pred = '+ str(pred))
#     # loop over test data
#     for i in range(len(B)):
#         # Get nearest neighbor
#         nn_index = sess.run(pred, feed_dict={xtr: A, xte: B[i, :]})
#         # Get nearest neighbor class label and compare it to its true label
#         print "Test", i, "Prediction:", np.argmax(Ytr[nn_index]), \
#             "True Class:", np.argmax(Yte[i])
#         # Calculate accuracy
#         if np.argmax(Ytr[nn_index]) == np.argmax(Yte[i]):
#             accuracy += 1./len(Xte)
#     print "Done!"
#     print "Accuracy:", accuracy

Instructions for updating:
Use `argmin` instead
dis = [ 12.   3.   3.   9.  12.]
pred = 1


In [ ]:
#--------Test Softmax-------#


pred = tf.nn.softmax(tf.matmul(x, W) + b) # Softmax


# Launch the graph
with tf.Session() as sess:
    sess.run(init)

    dis = sess.run(distance, feed_dict={xtr: A, xte: B[0]})
    print('dis = '+ str(dis))

In [2]:
#-----Softmax Test------#
sx = tf.nn.softmax([-6.0,0.0,3.0,6.0]) # Softmax

with tf.Session() as sess:
    ary =  sess.run(sx)
    
print(sum(ary))

0.999999989359


In [26]:
#-----  A * B  is not A.matmul(B)------#
A = [ [1.0,2.0, 3.0], 
      [2.0,2.0, 2.0]] 

B = [ [3,3, 3 ],
      [10, 20, 30 ]]

y = tf.placeholder(tf.float32, [None, 3]) 


   
with tf.Session() as sess:
    print sess.run( y , feed_dict={y: B} )
    print sess.run( y* (A), feed_dict={y: B})
    print sess.run( y* tf.log(A), feed_dict={y: B})

[[  3.   3.   3.]
 [ 10.  20.  30.]]
[[  3.   6.   9.]
 [ 20.  40.  60.]]
[[  0.           2.07944155   3.29583693]
 [  6.93147182  13.86294365  20.79441452]]


tf.argmax()
==========

In [4]:
import tensorflow as tf
B = [ [ 3,  7,  2 ,99,200,3],
      [10, 20, 30 ,1 ,  3,2 ]]

m = tf.argmax(B, 1)

print tf.Session().run(m)

[4 2]


tf.unstack()
==========

In [7]:
#-----Test for unstack------#
import tensorflow as tf

A = [ [4,6, 5 ], 
      [2,2, 2],
     [0,0, 0 ],
     [4,4, 4 ],
     [5, 5, 5 ]
    ]

u = tf.unstack(A, axis = 0)
t = tf.unstack(A, axis = 1)
# Launch the graph
with tf.Session() as sess:
    print('u = ' + str( sess.run(u) ) )
    print('t = ' + str( sess.run(t) ) )
    

u = [array([4, 6, 5], dtype=int32), array([2, 2, 2], dtype=int32), array([0, 0, 0], dtype=int32), array([4, 4, 4], dtype=int32), array([5, 5, 5], dtype=int32)]
t = [array([4, 2, 0, 4, 5], dtype=int32), array([6, 2, 0, 4, 5], dtype=int32), array([5, 2, 0, 4, 5], dtype=int32)]


In [13]:
#-----Test for unstack------#
import tensorflow as tf

A = [  
      [ 
            [4,6, 5 ], 
            [2,2, 2] 
      ],
      [
         [0,0, 0 ],
         [4,4, 4 ]
         
      ],
      [
          [5, 5, 5 ],
          [6, 6, 6]
      ]
    ]

u = tf.unstack(A, 3)
# t = tf.unstack(A, 3, axis = 1)
# Launch the graph
with tf.Session() as sess:
    print('u = ' + str( sess.run(u) ) )
#     print('t = ' + str( sess.run(t) ) )
    

u = [array([[4, 6, 5],
       [2, 2, 2]], dtype=int32), array([[0, 0, 0],
       [4, 4, 4]], dtype=int32), array([[5, 5, 5],
       [6, 6, 6]], dtype=int32)]


In [3]:
#-----Test for random_normal------#
import tensorflow as tf

in_size = 3
out_size = 7 
ran_norm = tf.random_normal([in_size, out_size])
                            
with tf.Session() as sess:
    print('ran_norm = ' + str( sess.run(ran_norm) ) )

ran_norm = [[ 1.07031202 -0.61447394  0.23734196  0.86800736  0.03217022 -0.73966962
   0.45953852]
 [ 0.49735177  0.31650037  1.19679868 -0.10334399 -0.92777944 -1.43667126
   0.82876015]
 [ 0.25597674  0.29477075  1.01669419  0.80626851  1.29378831  0.30296737
  -0.08579311]]
